AllCops:
  Exclude:
    - vendor/**

MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30
